### ISSUE TITLE
Including extra fields in VEP CSQ tag

### ISSUE THREAD

**Issue by a113n** [quinlan-lab/vcf2db#13]
Right now vcf2db supports the following VEP fields:

> Consequence|Codons|Amino_acids|Gene|HGNC|Feature|EXON|PolyPhen|SIFT

But is it possible to extend the software to parse other fields from VEP, such as ExAC frequency, 1000G frequency?

Thanks!

**Comment by brentp** [comment]
Yes, let me figure out how to add this.

**Comment by a113n** [comment]
That would be great 👍

**Comment by matthdsm** [comment]
to take this a bit further, would it be possible for vcf2db to include all annotations inside the tag? We have vcf files annotated with a bunch of fields from dbNSFP and and other VEP plugins and we'd like to import those too.

Thanks!

**Comment by matthdsm** [comment]
Thanks for the work you did to solve this issue. Would it be possible to update the conda recipe, so we can easily install the latest version?

Thanks again!

**Comment by matthdsm** [comment]
Hi,
Is there a timeline available for a new release of vcf2db and the geneimpacts library that includes support for arbitrary vep annotations?

Thanks
M

**Comment by brentp** [comment]
I have just opened the PRs to bioconda for geneimpacts and vcf2db. They should go in today.

**Comment by matthdsm** [comment]
Allright! Thanks!

**Comment by brentp** [comment]
this is in vcf2db for some time now.
