### ISSUE TITLE
feature request - parallelization

### ISSUE THREAD

**Issue by matthdsm** [quinlan-lab/vcf2db#16]
Hi,

Would it be possible to include a parallelization option (cfr gemini load) to spread the workload over multiple cores?

Thanks
M

**Comment by davemcg** [comment]
I also wonder if this is possible - or is there any way to merge chr split gemini databases?

**Comment by davemcg** [comment]
I suppose the simplest thing to do is just use `gemini load --skip-gerp-bp --skip-cadd --skip-gene-tables -t VEP --cores 16 -v my.vcf.gz my.gemini.db` ?

**Comment by brentp** [comment]
I don't want to support this because vcf2db is already complex enough. someone else could write an external tool that loads by region (using vcf2db) and then merges using sqlite machinery.

**Comment by davemcg** [comment]
Something like this? 

```
Split massive vcf into N pieces by position

Create N gemini databases with vcf2db

sqlite3 gemini_0001.db '.dump' >> tmp
sqlite3 gemini_0002.db '.dump' >> tmp
...
sqlite3 gemini_N.db '.dump' >> tmp
sqlite3 final.gmeini.db '.import tmp'
```
