### ISSUE TITLE
expand sample values into table of n-variants*n-samples rows

### ISSUE THREAD

**Issue by brentp** [quinlan-lab/vcf2db#2]
Currently, the loader creates a table for `--expand` columns that is n-variants rows by n-samples columns.
It will probably make it easier to write the SQL if it is n-variants \* n-samples rows. So a query would look like

``` sql
SELECT v.chrom, v.start, v.end, g.value FROM variants v, genotypes g WHERE \
    v.variant_id = g.variant_id and g.sample_id = 23
```

instead of (currently)

``` sql
SELECT v.chrom, v.start, v.end, g.sample_23 FROM variants v, genotypes g WHERE \
    v.variant_id = g.variant_id
```

where the latter is difficult for, e.g. sqlalchemy as we'll have to use gettattr(genotypes, "sample_23") for samples that are filled programattically.
This will get around the limitation of number of columns per database table that is present in the current setup. If, e.g. we have 100 million variants and 10K samples. sqlite has a limit of 2^64 rows, so we'd be far from that, and more likely to hit the maximum database size.

I think the performance characteristics should be similar, though maybe I'll do a test on 1KG data to see.

thoughts @arq5x , @bw2 ?

**Comment by brentp** [comment]
given an example from @arq5x :
`sites that are het in mom het and dad and homalt in kid.`

currently:

``` sql
SELECT v.chrom, v.start, v.end, g.sample_23 FROM variants v, gt_types g WHERE \
    v.variant_id = g.variant_id AND g.mom = HET AND g.dad = HET and g.kid = HET
```

becomes:

``` sql
select variant_id from gt_types where (sample_id = mom and value = HET) \
                                     or (sample_id = dad and value = HET) \
                                     or (sample_id = kid and value = HOM_ALT) \
                                     having count(variant_id) = 3;

```

And I'm not sure that's right. So, much simpler to do this type of query given the current setup.

**Comment by bw2** [comment]
I think the [n-variants rows \* n-samples columns] table is best for queries that need to return variants filtered by one or more genotypes (like your example), but the n-variants \* n-samples rows table could be
 good for queries on samples (like counting samples with particular attributes in a particular region), and these would be difficult to do vice-versa.

**Comment by arq5x** [comment]
For family studies the  [n-variants rows \* n-samples columns] table is best. However, it scales very poorly, as for query performance, one needs to create an index on each of the n-samples columns \* k genotype columns.
