### ISSUE TITLE
using vcf2db with mysql/postgres

### ISSUE THREAD

**Issue by matthdsm** [quinlan-lab/vcf2db#26]
Hi Brent,

Just a litte question;
When using vcf2db with postgres/mysql, is it possible to add data to an existing db? or does this option need a clean database/vcf?

Being able to add samples (cfr. Gemini) would be great to set up a collection of variants.

Thanks
M

**Comment by brentp** [comment]
it will have to be a new database. Adding samples is difficult because we don't know that the set of variants will be the same.

**Comment by matthdsm** [comment]
Too bad! thanks for the answer!
M
