### ISSUE TITLE
vcf2db not copying all fields from the INFO

### ISSUE THREAD

**Issue by jgrady-omico** [quinlan-lab/vcf2db#44]
Hi Brent,

I am using vcfanno and vcf2db to annotate various fields, including CADD scores.
vcfanno is correctly annotating the CADD score. However, vcf2db does not appear to be transferring the CADD scores into the gemini database.

An example vcf and ped file are attached. The command I used to produce the db is:
python ~/software/vcf2db/vcf2db.py test.vcf.gz ped.txt  test.db

Then I try to read from the db using

gemini query -q "SELECT cadd_phred FROM variants --header --show-samples --sample-delim ;" test.db

which returns blank entries.

I deliberately used cadd_phred as the field name to be consistent with the previous gemini field names - is it possible it isn't copying because the default gemini field names are reserved? Is it possible to get vcf2db to populate these fields in the same way gemini does? Or am I barking up the wrong tree...

Many thanks,

John.

[ped.txt](https://github.com/quinlan-lab/vcf2db/files/2012032/ped.txt)
[test.vcf.gz](https://github.com/quinlan-lab/vcf2db/files/2012033/test.vcf.gz)

**Comment by brentp** [comment]
I have pushed a fix for this. Thanks very much for the nice test-case and for reporting.
