### ISSUE TITLE
citing VCF2DB

### ISSUE THREAD

**Issue by Phillip-a-richmond** [quinlan-lab/vcf2db#49]
Brent,
We are preparing a manuscript for resubmission and within we are providing a full, detailed pipeline which integrates tools from the Quinlan lab, including:

VCFAnno, VCF2DB, GEMINI. 

VCFAnno and GEMINI have papers to cite, but how would you like VCF2DB cited? The GitHub page?

Thanks,
Phil

**Comment by brentp** [comment]
Hi Phil, that's great to hear. I think that citing the gemini paper is sufficient and if you care to cite vcf2db, that would be directly to the github repo.
Thanks!

**Comment by Phillip-a-richmond** [comment]
Okay and with VCF2DB do you plan on versioning it? I think the last pull I did was January 22nd, 2018 after you added the --a-ok option

**Comment by brentp** [comment]
You could just reference the commit that you used. We'll get out a versioned release this year, but it won't be for a couple months, I think.
