### ISSUE TITLE
VEP SIFT

### ISSUE THREAD

**Issue by brainstorm** [quinlan-lab/vcf2db#5]
Hello @brentp,

I'm running VEP on a small VCF, testing for bcbio, with this [shell script](https://github.com/wwcrc/icgc_sv/blob/master/bin/vep_vcf.sh) which seems to include this VEP header in the resulting VCF:

```
##VEP=v83 cache=. db=homo_sapiens_core_83_38@ensembldb.ensembl.org ESP=20141103 gencode=GENCODE 24 sift=sift5.2.2 dbSNP=144 HGMD-PUBLIC=20152 ClinVar=201510 COSMIC=74 assembly=GRCh38.p5 genebuild=2014-07
```

But I'm getting this traceback along the way:

```
Traceback (most recent call last):
  File "/home/rvalls/bin/gemini_vcf2db.py", line 654, in <module>
    blobber=blobber)
  File "/home/rvalls/bin/gemini_vcf2db.py", line 156, in __init__
    self.load()
  File "/home/rvalls/bin/gemini_vcf2db.py", line 215, in load
    i = self._load(self.cache, create=True, start=1)
  File "/home/rvalls/bin/gemini_vcf2db.py", line 208, in _load
    self.insert(variants, expanded, keys, i, create=create)
  File "/home/rvalls/bin/gemini_vcf2db.py", line 235, in insert
    v in variants)
  File "/home/rvalls/bin/gemini_vcf2db.py", line 583, in gene_info
    top = geneimpacts.Effect.top_severity(impacts)
  File "/home/rvalls/.miniconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 299, in top_severity
    effects = sorted(effects)
  File "/home/rvalls/.miniconda/lib/python2.7/functools.py", line 60, in <lambda>
    ('__lt__', lambda self, other: self <= other and not self == other),
  File "/home/rvalls/.miniconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 280, in __le__
    if (self.sift_value or 10000) < (other.sift_value or 10000):
  File "/home/rvalls/.miniconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 514, in sift_value
    return float(self.effects['SIFT'].split("(")[1][:-1])
KeyError: 'SIFT'
```

Seems that `geneimpacts` is expecting a tuple from SIFT (that's why I tried with [`b` option in the shell script](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_sift)). 

Do you have a minimal VCF file you used to run your `vcf2db` script so I can compare/fix re-iterate on it?

Thanks in advance!

@ohofmann

**Comment by brentp** [comment]
I will have a look. Previously, sift looked like "possibly_damaging(0.5)"
you can have a look at [the test.vcf](https://github.com/quinlan-lab/vcf2db/blob/master/tests/test.vcf) in this repo.

How did you run VEP? And what is the CSQ header line? If you can share a small part of the VCF, then I'll see what is the problem.

thanks for reporting.

**Comment by brainstorm** [comment]
Hello @brentp!

I tried to run VEP in the following shell script, indicating `--sift b` and `--fields Consequence, CSQ, EFF, ANN, SIFT`:

https://github.com/wwcrc/icgc_sv/blob/master/bin/vep_vcf.sh

```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Consequence">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1 sample2
```

Thanks for pointing to the test vcf, didn't see it.

**Comment by brainstorm** [comment]
I see that I'm missing `SIFT` in the header line, not sure why is that since I passed the flags. Pity that VEP does not include a `VEPcmd` in the header lines.

How did you run VEP?

**Comment by brentp** [comment]
we use the command here: http://gemini.readthedocs.io/en/latest/content/functional_annotation.html#running-vep

it doesn't look like you have the correct use of `--fields` to me. CSQ, EFF, and ANN are the names of the info field and don't need to be specified.

**Comment by brainstorm** [comment]
Right on, thanks Brent, that was it (wrong field names), sorry to bother you :-/

Just cosmetic I guess, but I'm getting warnings since the last UTF commit you pushed a few days ago:

```
/home/rvalls/.miniconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '0d31a44f_1fc5_43a2_9633_3...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
(...)
```

**Comment by brentp** [comment]
do you have the very latest commit? I had a few in succession with unicode stuff. But there may still be some issues.

**Comment by brainstorm** [comment]
Yes, up to this commit (`HEAD` at the time of writing this):

```
commit d144a9e01f30d930273c4c4f4e184f9165f9ef5f
Author: Brent Pedersen <bpederse@gmail.com>
Date:   Thu May 5 10:42:32 2016 -0600

    update readme with installation
```

**Comment by brentp** [comment]
ok. I'll have a look.
