### ISSUE TITLE
vcf2db converting string values to float

### ISSUE THREAD

**Issue by matthdsm** [quinlan-lab/vcf2db#51]
Hi Brent,

I'm encountering the following issue.
When creating a db from a vcf file annotated using vcfanno, I get the following error:
`sqlalchemy.exc.StatementError: (exceptions.ValueError) could not convert string to float:...`

This error is cause by values such as `VEST3_score=0.123,0.122` in the vcf, even though the header states it should be treated as a `string` value. Did any logic in parsing these values change recently? I've been using dbNSFP and vcf2db for quite some time now, and I hadn't encountered this issue yet.

ref bcbio issue: https://github.com/bcbio/bcbio-nextgen/issues/2511#issuecomment-423912677

cheers
M

**Comment by brentp** [comment]
I'll have a look but can you share a small vcf to recreate?

**Comment by matthdsm** [comment]
Sure, you can find it [here](https://github.com/quinlan-lab/vcf2db/files/2413916/NA12878K12.vcf.gz).

FYI, I'm using both the latest bioconda vcf2db and geneimpacts
```
# Name                    Version                   Build  Channel
vcf2db                    2018.01.23               py27_0    bioconda
geneimpacts               0.3.3                    py27_0    bioconda
```

The exact traceback can be found in the linked bcbio issue.
Thanks for looking into this.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brent,

Did you find time to have a quick look at this? As far as I've found, the issue comes from dbNSFP annotations made by vcfanno.

Thanks
M

**Comment by matthdsm** [comment]
Hi Brent,

Just a little bump, thanks for looking into this!

Cheers
M

**Comment by brentp** [comment]
this is caused by:
```
##INFO=<ID=gnomAD_genomes_AF,Number=1,Type=String,Description="calculated by first of overlapping values in column 217 from /home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/variation/dbNSFP.txt.gz">
```
rather than `first`, you could use `self`. vcf2db tries to convert any field that looks like an allele frequency to a float. and you have empty values as: "." 
I can probably add more logic to deal with this, but saving af columns as strings seems the root issue and is upstream of vcf2db

**Comment by brentp** [comment]
actually, it was a trivial fix so I just made it.

vcf2db is turning into a bunch of checks that really are a consequence of 1) abusing vcf format by putting what are obvious numeric values into strings 2) guessing at what the user wants 3) trying to shoe-horn VCF into a database.

I would suggest to make sure the types in you VCF are exactly what you want, so, e.g. gnomAD_genomes_AF is representing something that's actually a float, so it'd remove downstream problems if it was used as a float (e.g. by using self in vcfanno).

**Comment by matthdsm** [comment]
Hi Brent,

Thanks for the fix! I thought that `self` was only to be used with vcf files? dbNSFP is a tabular file, so I didn't know that would work.
I'll play around a bit with this.

Thanks again!
Cheers
M

**Comment by brentp** [comment]
I think it might work since dbNSFP has (I think) ref and alt columns.

**Comment by matthdsm** [comment]
Hi Brent,
Just an FYI, annotating with dbNSFP using `self` does work, but causes `vcf2db.py` to fail because of some composite float values. So unless we find a way to parse dbNSFP to represent each value as a separate line, I don' really thinks it's a viable option.

Cheers
M

**Comment by brentp** [comment]
hmm. good to know. thanks for looking into it. hopefully the fix above will be good enough for now.
