### ISSUE TITLE
Incrementally push to production level databases

### ISSUE THREAD

**Issue by matthdsm** [quinlan-lab/vcf2db#63]
Hi Brent,

Do you think it's possible/viable to incrementally push new data to a postgres db using vcf2db?

Thanks for the info
Cheers
M

**Comment by brentp** [comment]
no. not to the same table anyway. it could push to different tables in the same db, but i don't think that's what you want. we thought about this at one point, but it's outside the scope of vcf2db as it requires resolving (or ignoring) the n+1 problem in which we don't t reliably know the genotype of the n samples when a new (+1) sample has a not before seen variant.

**Comment by matthdsm** [comment]
Hi Brent,

Thanks for the answer. I thought so already. Added new samples would require rerunning the joint genotyping is suppose.

Thanks anyway!
Cheers
M
